// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router';

// Import Routes
import { Route as rootRoute } from './routes/__root';

// Create Virtual Routes
const HomeLazyImport = createFileRoute('/home')();
const AuthLazyImport = createFileRoute('/')();

// Create/Update Routes

const HomeLazyRoute = HomeLazyImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home.lazy').then(d => d.Route));

const AuthLazyRoute = AuthLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth.lazy').then(d => d.Route));

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof AuthLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/home': {
      preLoaderRoute: typeof HomeLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([AuthLazyRoute, HomeLazyRoute]);
